# Generated by Django 4.1.2 on 2023-01-19 18:49

from django.db import migrations, models
import task_manager.services.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_date_of_birth_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_picture',
            field=models.ImageField(null=True, storage=task_manager.services.storage_backends.public_storage, upload_to=''),
        ),
    ]
